name: Sync SSH Keys

on:
  push:
    paths:
      - 'authorized_keys'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout keys
        uses: actions/checkout@v4

      - name: Validate key format
        run: |
          if ! grep -E "^ssh-(ed25519|rsa) AAAA[0-9A-Za-z+/]+[=]{0,3}( .*)?$" authorized_keys; then
            echo "❌ Invalid SSH key format detected!"
            echo "Keys must start with 'ssh-ed25519' or 'ssh-rsa' followed by valid key material"
            exit 1
          fi

      - name: Deploy keys
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: authorized_keys
          target: /tmp/authorized_keys

      - name: Apply keys and log
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /tmp/authorized_keys /etc/ssh/auth_keys/
            sudo chown root:root /etc/ssh/auth_keys/authorized_keys
            sudo chmod 644 /etc/ssh/auth_keys/authorized_keys
            echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') - Keys updated by $GITHUB_ACTOR via $GITHUB_SHA" | sudo tee -a /var/log/ssh-key-updates.log
