name: Sync SSH keys to VPS

# Trigger on any change to authorized_keys2 (or to main branch)
on:
  push:
    paths:
      - 'authorized_keys2'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) checkout your repo
      - uses: actions/checkout@v4

      # 2) start an ssh-agent & add the private key
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) add your VPS to known_hosts to avoid host‑key prompt
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 4) copy the file to ~/.ssh/authorized_keys2 on the VPS
      - name: Sync authorized_keys2
        run: |
          scp -P ${{ secrets.SSH_PORT }} authorized_keys2 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/.ssh/authorized_keys2

      # 5) ensure correct permissions on the remote file
      - name: Fix remote permissions
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "chmod 600 ~/.ssh/authorized_keys2 && chown ${{ secrets.SSH_USER }} ~/.ssh/authorized_keys2"
