name: Sync SSH Keys

on:
  push:
    paths:
      - 'authorized_keys'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout keys
        uses: actions/checkout@v4

      - name: Deploy keys
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: authorized_keys
          target: /tmp/authorized_keys

      - name: Apply keys
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /tmp/authorized_keys /etc/ssh/auth_keys/
            sudo chown root:root /etc/ssh/auth_keys/authorized_keys
            sudo chmod 644 /etc/ssh/auth_keys/authorized_keys
